/**
 * Created by Administrator on 2016/8/16.
 */
var data=[
    {"id":"1","name":"（商城专供）搭售 蜂蜜3+1组","img":"../img/product/list2.jpg","price":"￥84","point":"","ask":"枣花蜜 X1槐花蜜 X1荆条蜜 X1赠品蜂蜜 X1"},
    {"id":"2","name":"芬狄诗贡缎提花4+4+4特惠组","img":"../img/product/list3.jpg","price":"￥398","point":"网购送3积分","ask":"赠品：花彩依梦四件套*1 X1主商品：花舞盛典四件套 X1 +华丽乐章四件套 X1 "},
    {"id":"3","name":"壮元海南极磷虾酱家庭组（30罐）","img":"../img/product/list4.jpg","price":"￥298","point":"网购送2积分","ask":"壮元海南极磷虾酱135g/罐 XO"},
    {"id":"4","name":"（闪购）哈肉联红肠特惠组","img":"../img/product/list5.jpg","price":"￥99","point":"","ask":"哈肉联经典风味红肠 XO"},
    {"id":"5","name":"小余儿花儿朵朵开雪纺上衣套组（新）","img":"../img/product/list6.jpg","price":"￥299","point":"网购送2积分","ask":"赠品：百搭七分蕾丝打底裤共3件 X1蓝色花朵*1灰色花朵*1粉色花朵*1共3件 X1"},
    {"id":"6","name":"美眠宝零压力太空椅2+2升级套组","img":"../img/product/list7.jpg","price":"￥398","point":"网购送3积分","ask":"美眠宝零压力太空椅 X2 便携折叠凳  X2"},
    {"id":"7","name":"GUCCI飞行员款经典太阳镜","img":"../img/product/list8.jpg","price":"￥999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"8","name":"GUCCI飞行员款经典太阳镜","img":"../img/product/list9.jpg","price":"￥999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"9","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list10.jpg","price":"￥999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"10","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list11.jpg","price":"￥999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"11","name":"艾氏黑蜂蜂蜜超值套组","img":"../img/product/list12.jpg","price":"￥999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"12","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list13.jpg","price":"￥3999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"13","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list14.jpg","price":"￥2999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"14","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list15.jpg","price":"￥1999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"15","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list16.jpg","price":"￥919","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"16","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list17.jpg","price":"￥129","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"17","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list18.jpg","price":"￥929","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"18","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list19.jpg","price":"￥949","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"19","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list20.jpg","price":"￥29","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"20","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list21.jpg","price":"￥1399","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"21","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list22.jpg","price":"￥19","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"22","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list23.jpg","price":"￥929","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"23","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list24.jpg","price":"￥999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"24","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list25.jpg","price":"￥999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"25","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list26.jpg","price":"￥999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"26","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list27.jpg","price":"￥1999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"27","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list28.jpg","price":"￥2999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"28","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list29.jpg","price":"￥3999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"29","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list30.jpg","price":"￥4999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"30","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list31.jpg","price":"￥299","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"31","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list32.jpg","price":"￥599","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"32","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list33.jpg","price":"￥799","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"34","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list34.jpg","price":"￥299","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"35","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list35.jpg","price":"￥199","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"36","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list36.jpg","price":"￥3399","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"37","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list37.jpg","price":"￥929","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"38","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list38.jpg","price":"￥23999","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"39","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list39.jpg","price":"￥939","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"},
    {"id":"40","name":"GUCCI经典条纹织带太阳镜","img":"../img/product/list40.jpg","price":"￥239","point":"网购送9积分","ask":"GUCCI太阳镜 X1质保卡 X1眼镜布 X1 说明书 X1"}

];